version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  ff4j-redis:
    image: ff4j/ff4j-sample-springboot2x-redis
    ports:
      - "8080:8080"
    environment:
      FF4J_REDIS_URI: redis://redis:6379
